name: Terraform Plan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main  # ✅ This was missing!

jobs:
  terraform:
    name: 'Terraform Format, Init & Plan'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
