name: Terraform Apply

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform Init, Validate, and Apply'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

        
      - name: Set up AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AKIASJRSHQKBGS27PQK3}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.yW5xkMQmFU+mKUi+fnnm4B1PZ4+a7MxjAXOI4joA }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          echo "AWS credentials set"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Apply
        run: terraform apply -auto-approve
